services:
  webserver:
    image: nginx:latest
    container_name: webserver
    ports:
      - "80:80"
      - "8080:80"
      - "5443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - ./html:/usr/share/nginx/html
    restart: always

  cacti-db:
    image: linuxserver/mariadb:arm32v7-10.6.13
    container_name: cacti-db
    environment:
      - MYSQL_ROOT_PASSWORD=cacti
      - MYSQL_DATABASE=cacti
      - MYSQL_USER=cactiuser
      - MYSQL_PASSWORD=cactipass
    volumes:
      - db_data:/var/lib/mysql
      - ./cacti/my.cnf:/etc/my.cnf
    restart: always

  cacti-web:
    build: ./cacti
    container_name: cacti-web
    environment:
      - DB_HOST=cacti-db
      - DB_NAME=cacti
      - DB_USER=cactiuser
      - DB_PASS=cactipass
      - TZ=Asia/Jakarta
    depends_on:
      - cacti-db
    volumes:
      - cacti_data:/var/www/html/cacti/rra
    restart: always

  # RUST DESK
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    volumes:
      - ./data:/root
    # Explicit IPv4 Port Mapping
    ports:
      - "0.0.0.0:21115:21115/tcp"
      - "0.0.0.0:21116:21116/tcp"
      - "0.0.0.0:21116:21116/udp"
      - "0.0.0.0:21118:21118/tcp"
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    # Explicit IPv4 Port Mapping
    ports:
      - "0.0.0.0:21117:21117/tcp"
      - "0.0.0.0:21119:21119/tcp"
    restart: unless-stopped

volumes:
  db_data:
  cacti_data:
